default:
  scale_mpl: 1.0
  bias_mpl: 0.0
  scale_energy_wh: 1.0
  bias_energy_wh: 0.0
  scale_damage: 1.0
  bias_damage: 0.0
  offset: {}
  source_domain: sim_pybullet
  target_domain: platform_econ

sim_pybullet:
  scale_mpl: 1.0
  bias_mpl: 0.0
  scale_energy_wh: 1.0
  bias_energy_wh: 0.0
  scale_damage: 1.0
  bias_damage: 0.0
  source_domain: sim_pybullet
  target_domain: platform_econ

sim_isaac:
  scale_mpl: 1.0
  bias_mpl: 0.0
  scale_energy_wh: 1.0
  bias_energy_wh: 0.0
  scale_damage: 1.0
  bias_damage: 0.0
  source_domain: sim_isaac
  target_domain: platform_econ

real_ros:
  scale_mpl: 0.95
  bias_mpl: 0.0
  scale_energy_wh: 1.2
  bias_energy_wh: 0.0
  scale_damage: 1.1
  bias_damage: 0.0
  source_domain: real_ros
  target_domain: platform_econ

real_isaac:
  scale_mpl: 0.9
  bias_mpl: 0.0
  scale_energy_wh: 1.1
  bias_energy_wh: 0.0
  scale_damage: 1.05
  bias_damage: 0.0
  source_domain: real_isaac
  target_domain: platform_econ

pybullet_smoke:
  scale_mpl: 1.0
  bias_mpl: 0.0
  scale_energy_wh: 0.2
  bias_energy_wh: 0.0
  scale_damage: 0.5
  bias_damage: 0.0
  offset: {}
  source_domain: sim_pybullet
  target_domain: platform_econ

isaac_stub:
  scale_mpl: 1.0
  bias_mpl: 0.0
  scale_energy_wh: 1.0
  bias_energy_wh: 0.0
  scale_damage: 1.0
  bias_damage: 0.0
  offset: {}
  source_domain: isaac
  target_domain: platform_econ
